unique_ids:
  assets:
    standard-page.html: NSV4C3UR6JU4PJP5NDVPXVRPKK2YPNV7
    theme.css: S3SGVYMLC5D6XXVAGX6HSO3GMG44VAW5
  forms:
    Form1: 5D36EQVPDJIF4ALUQQPAXYNWXIVKXXGM
  modules: {}
  scripts: {}
  server_modules: {}
